services:
  frontend:
    build: 
      context: ./frontend
    ports:
      - "5173:5173"
    env_file:
      - ./.env

  backend:
    build: 
      context: ./backend
    ports:
      - "4000:4000"
    env_file:
      - ./.env

  admin:
    build: 
      context: ./admin
    ports:
      - "5174:5174"
    env_file:
      - ./.env
