apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-deployment
  labels:
    app: frontend-d
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-admin
  template:
    metadata:
      labels:
        app: frontend-admin
    spec:
      containers:
      - name: admin-container
        image: kartheekknrs/admin-image-1:latest
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: myconfigmap
