apiVersion: v1
kind: ConfigMap
metadata:
  name: myconfigmap
data:
  MONGODB_URI: "*********************************************"
  PORT: "4000"
  VITE_HOST: "0.0.0.0"
  VITE_BACKEND_URL: "http:// <your backend path or ip>"
  JWT_SECRET: "*************"
  ADMIN_EMAIL: "*****************"
  ADMIN_PASSWORD: "***********"
  CLOUDINARY_API_KEY: "**************"
  CLOUDINARY_NAME: "**************"
  CLOUDINARY_SECRET_KEY: "**********************"

