apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-deployment
  labels:
    app: frontend-d
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend-container
        image: kartheekknrs/frontend-image-1:latest
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: myconfigmap
